export const categories = [
    { name: 'Living Room', type: 'Sofas Sofa Beds', color: 'red' },
    { name: 'Living Room', type: 'Sofas Sofa Beds', color: 'blue' },
    { name: 'Living Room', type: 'Sofas Sofa Beds', color: 'green' },
    { name: 'Living Room', type: 'Sofas Sofa Beds', color: 'white' },
    { name: 'Living Room', type: 'Sofas Sofa Beds', color: 'black' },
    { name: 'Living Room', type: 'Armchairs', color: 'red' },
    { name: 'Living Room', type: 'Armchairs', color: 'blue' },
    { name: 'Living Room', type: 'Armchairs', color: 'green' },
    { name: 'Living Room', type: 'Armchairs', color: 'white' },
    { name: 'Living Room', type: 'Armchairs', color: 'black' },
    { name: 'Living Room', type: 'Cocktail Tables', color: 'red' },
    { name: 'Living Room', type: 'Cocktail Tables', color: 'blue' },
    { name: 'Living Room', type: 'Cocktail Tables', color: 'green' },
    { name: 'Living Room', type: 'Cocktail Tables', color: 'white' },
    { name: 'Living Room', type: 'Cocktail Tables', color: 'black' },
    { name: 'Living Room', type: 'Tv Units', color: 'red' },
    { name: 'Living Room', type: 'Tv Units', color: 'blue' },
    { name: 'Living Room', type: 'Tv Units', color: 'green' },
    { name: 'Living Room', type: 'Tv Units', color: 'white' },
    { name: 'Living Room', type: 'Tv Units', color: 'black' },
    { name: 'Living Room', type: 'Bookcases and Cabinets', color: 'red' },
    { name: 'Living Room', type: 'Bookcases and Cabinets', color: 'blue' },
    { name: 'Living Room', type: 'Bookcases and Cabinets', color: 'green' },
    { name: 'Living Room', type: 'Bookcases and Cabinets', color: 'white' },
    { name: 'Living Room', type: 'Bookcases and Cabinets', color: 'black' },
    { name: 'Living Room', type: 'Consoles Occasional Furniture', color: 'red' },
    { name: 'Living Room', type: 'Consoles Occasional Furniture', color: 'blue' },
    { name: 'Living Room', type: 'Consoles Occasional Furniture', color: 'green' },
    { name: 'Living Room', type: 'Consoles Occasional Furniture', color: 'white' },
    { name: 'Living Room', type: 'Consoles Occasional Furniture', color: 'black' },

    { name: 'Dining Room', type: 'Tables', color: 'red' },
    { name: 'Dining Room', type: 'Tables', color: 'blue' },
    { name: 'Dining Room', type: 'Tables', color: 'green' },
    { name: 'Dining Room', type: 'Tables', color: 'white' },
    { name: 'Dining Room', type: 'Tables', color: 'black' },
    { name: 'Dining Room', type: 'Chairs Stools Benches', color: 'red' },
    { name: 'Dining Room', type: 'Chairs Stools Benches', color: 'blue' },
    { name: 'Dining Room', type: 'Chairs Stools Benches', color: 'green' },
    { name: 'Dining Room', type: 'Chairs Stools Benches', color: 'white' },
    { name: 'Dining Room', type: 'Chairs Stools Benches', color: 'black' },
    { name: 'Dining Room', type: 'Dining Room Storage', color: 'red' },
    { name: 'Dining Room', type: 'Dining Room Storage', color: 'blue' },
    { name: 'Dining Room', type: 'Dining Room Storage', color: 'green' },
    { name: 'Dining Room', type: 'Dining Room Storage', color: 'white' },
    { name: 'Dining Room', type: 'Dining Room Storage', color: 'black' },

    { name: 'Desk', type: 'Desks', color: 'red' },
    { name: 'Desk', type: 'Desks', color: 'blue' },
    { name: 'Desk', type: 'Desks', color: 'green' },
    { name: 'Desk', type: 'Desks', color: 'white' },
    { name: 'Desk', type: 'Desks', color: 'black' },
    { name: 'Desk', type: 'Office Chairs', color: 'red' },
    { name: 'Desk', type: 'Office Chairs', color: 'blue' },
    { name: 'Desk', type: 'Office Chairs', color: 'green' },
    { name: 'Desk', type: 'Office Chairs', color: 'white' },
    { name: 'Desk', type: 'Office Chairs', color: 'black' },

    { name: 'Bedroom', type: 'Beds', color: 'red' },
    { name: 'Bedroom', type: 'Beds', color: 'blue' },
    { name: 'Bedroom', type: 'Beds', color: 'green' },
    { name: 'Bedroom', type: 'Beds', color: 'white' },
    { name: 'Bedroom', type: 'Beds', color: 'black' },
    { name: 'Bedroom', type: 'Wardrobes', color: 'red' },
    { name: 'Bedroom', type: 'Wardrobes', color: 'blue' },
    { name: 'Bedroom', type: 'Wardrobes', color: 'green' },
    { name: 'Bedroom', type: 'Wardrobes', color: 'white' },
    { name: 'Bedroom', type: 'Wardrobes', color: 'black' },

    { name: 'Outdoor Furniture', type: 'Sofas Armchairs', color: 'red' },
    { name: 'Outdoor Furniture', type: 'Sofas Armchairs', color: 'blue' },
    { name: 'Outdoor Furniture', type: 'Sofas Armchairs', color: 'green' },
    { name: 'Outdoor Furniture', type: 'Sofas Armchairs', color: 'white' },
    { name: 'Outdoor Furniture', type: 'Sofas Armchairs', color: 'black' },
    { name: 'Outdoor Furniture', type: 'Outdoor Furniture', color: 'red' },
    { name: 'Outdoor Furniture', type: 'Outdoor Furniture', color: 'blue' },
    { name: 'Outdoor Furniture', type: 'Outdoor Furniture', color: 'green' },
    { name: 'Outdoor Furniture', type: 'Outdoor Furniture', color: 'white' },
    { name: 'Outdoor Furniture', type: 'Outdoor Furniture', color: 'black' },
    { name: 'Outdoor Furniture', type: 'Outdoor Decoration', color: 'red' },
    { name: 'Outdoor Furniture', type: 'Outdoor Decoration', color: 'blue' },
    { name: 'Outdoor Furniture', type: 'Outdoor Decoration', color: 'green' },
    { name: 'Outdoor Furniture', type: 'Outdoor Decoration', color: 'white' },
    { name: 'Outdoor Furniture', type: 'Outdoor Decoration', color: 'black' },

    { name: 'Other Products', type: 'Lighting', color: 'red' },
    { name: 'Other Products', type: 'Lighting', color: 'blue' },
    { name: 'Other Products', type: 'Lighting', color: 'green' },
    { name: 'Other Products', type: 'Lighting', color: 'white' },
    { name: 'Other Products', type: 'Lighting', color: 'black' },
    { name: 'Other Products', type: 'Cushion', color: 'red' },
    { name: 'Other Products', type: 'Cushion', color: 'blue' },
    { name: 'Other Products', type: 'Cushion', color: 'green' },
    { name: 'Other Products', type: 'Cushion', color: 'white' },
    { name: 'Other Products', type: 'Cushion', color: 'black' },
    { name: 'Other Products', type: 'Rugs', color: 'red' },
    { name: 'Other Products', type: 'Rugs', color: 'blue' },
    { name: 'Other Products', type: 'Rugs', color: 'green' },
    { name: 'Other Products', type: 'Rugs', color: 'white' },
    { name: 'Other Products', type: 'Rugs', color: 'black' },
    { name: 'Other Products', type: 'Home Furnishings', color: 'red' },
    { name: 'Other Products', type: 'Home Furnishings', color: 'blue' },
    { name: 'Other Products', type: 'Home Furnishings', color: 'green' },
    { name: 'Other Products', type: 'Home Furnishings', color: 'white' },
    { name: 'Other Products', type: 'Home Furnishings', color: 'black' },
    { name: 'Other Products', type: 'Mirrors', color: 'red' },
    { name: 'Other Products', type: 'Mirrors', color: 'blue' },
    { name: 'Other Products', type: 'Mirrors', color: 'green' },
    { name: 'Other Products', type: 'Mirrors', color: 'white' },
    { name: 'Other Products', type: 'Mirrors', color: 'black' },


];


/*
export const categories: string[] = [
    'Sofas & Sofa beds',
    'Armchairs',
    'Cocktail Tables',
    'Bookcases and Cabinets',
    'Tables',
    'Chairs Stools Benches',
    'Dining Room Storage',
    'Desks',
    'Office Chairs',
    'Beds',
    'Wardrobes',
    'Rugs'
];
*/