
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footer/Footer";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/navbar/NavBar";
import StripeClient from "./StripteClient";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <StripeClient>
          <AuthProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthProvider>
          </StripeClient>
      </body>

    </html>
  );
}
