import { Role } from "src/auth/enum/roles.enum";
import { UserStatus } from "../enum/userStatus.enum";
import { UserClient } from "../enum/userClient.enum";


export const userMock = [
  {
    "name": "Carlos Mendoza",
    "email": "carlos.mendoza@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "552345656",
    "country": "México",
    "city": "Ciudad de México",
    "address": "Av. Reforma 123",
    "isAdmin": false,
    "uid": "Abc123",
    "createdAt": new Date(Date.now() - 26 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    "loginCount": 4,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Sofía Ramírez",
    "email": "sofia.ramirez@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "315678923",
    "country": "Colombia",
    "city": "Bogotá",
    "address": "Cra. 10 #45-67",
    "isAdmin": true,
    "uid": "Abc456",
    "createdAt": new Date(Date.now() - 36 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    "loginCount": 2,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Liam Smith",
    "email": "liam.smith@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "121255518",
    "country": "USA",
    "city": "New York",
    "address": "742 Evergreen Terrace",
    "isAdmin": true,
    "uid": "Abc789",
    "createdAt": new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    "loginCount": 1,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Emma Johnson",
    "email": "emma.johnson@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "441234567",
    "country": "UK",
    "city": "London",
    "address": "221B Baker Street",
    "isAdmin": false,
    "uid": "Abc101",
    "createdAt": new Date(Date.now() - 24 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    "loginCount": 35,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Mateo Fernández",
    "email": "mateo.fernandez@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "541123456",
    "country": "Argentina",
    "city": "Buenos Aires",
    "address": "Av. Corrientes 789",
    "isAdmin": true,
    "uid": "Abc102",
    "createdAt": new Date(Date.now() - 32 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 16 * 24 * 60 * 60 * 1000),
    "loginCount": 10,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Isabella González",
    "email": "isabella.gonzalez@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "346789012",
    "country": "España",
    "city": "Madrid",
    "address": "Calle Mayor 56",
    "isAdmin": false,
    "uid": "Abc103",
    "createdAt": new Date(Date.now() - 40 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    "loginCount": 72,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Noah Wilson",
    "email": "noah.wilson@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "612345693",
    "country": "Australia",
    "city": "Sydney",
    "address": "15 Harbour St.",
    "isAdmin": false,
    "uid": "Abc104",
    "createdAt": new Date(Date.now() - 48 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 24 * 24 * 60 * 60 * 1000),
    "loginCount": 55,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Ava Martínez",
    "email": "ava.martinez@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "787654371",
    "country": "Puerto Rico",
    "city": "San Juan",
    "address": "Calle Fortaleza 12",
    "isAdmin": true,
    "uid": "Abc105",
    "createdAt": new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    "loginCount": 93,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Lucas Dubois",
    "email": "lucas.dubois@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "331234546",
    "country": "Francia",
    "city": "París",
    "address": "Rue de Rivoli 30",
    "isAdmin": false,
    "uid": "Abc106",
    "createdAt": new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    "loginCount": 42,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Mia Rossi",
    "email": "mia.rossi@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "391234535",
    "country": "Italia",
    "city": "Roma",
    "address": "Via del Corso 100",
    "isAdmin": false,
    "uid": "Abc107",
    "createdAt": new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    "loginCount": 72,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Benjamin Kim",
    "email": "benjamin.kim@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "821012312",
    "country": "Corea del Sur",
    "city": "Seúl",
    "address": "Gangnam-gu 77",
    "isAdmin": true,
    "uid": "Abc108",
    "createdAt": new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    "loginCount": 22,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Elena Petrov",
    "email": "elena.petrov@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "749512339",
    "country": "Rusia",
    "city": "Moscú",
    "address": "Leninsky Prospekt 50",
    "isAdmin": false,
    "uid": "Abc109",
    "createdAt": new Date(Date.now() - 36 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    "loginCount": 10,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Ethan Brown",
    "email": "ethan.brown@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "141655547",
    "country": "Canadá",
    "city": "Toronto",
    "address": "Bloor St. 789",
    "isAdmin": false,
    "uid": "Abc110",
    "createdAt": new Date(Date.now() - 48 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    "loginCount": 85,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Chloe Müller",
    "email": "chloe.muller@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "491512352",
    "country": "Alemania",
    "city": "Berlín",
    "address": "Unter den Linden 5",
    "isAdmin": true,
    "uid": "Abc111",
    "createdAt": new Date(Date.now() - 28 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    "loginCount": 62,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  },
  {
    "name": "Gabriel Silva",
    "email": "gabriel.silva@example.com",
    //"password": "@securePass123",
    "password": "$2a$10$ABMbgePSEVnurftAg.2xw.scxEp1k.dxHgjecYG0ucJlD0LjTDQn.",
    "phone": "551198761",
    "country": "Brasil",
    "city": "São Paulo",
    "address": "Av. Paulista 900",
    "isAdmin": false,
    "uid": "Abc112",
    "createdAt": new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    "lastLogin": new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    "loginCount": 45,
    "role": Role.User,
    "status": UserStatus.ACTIVE,
    "client": UserClient.STANDARD
  }
]
